src/main/java/in/twizmwaz/cardinal/Cardinal.java, src/main/java/in/twizmwaz/cardinal/Chat/AdminChat.java, src/main/java/in/twizmwaz/cardinal/Chat/Chat.java, src/main/java/in/twizmwaz/cardinal/Chat/GlobalChat.java, src/main/java/in/twizmwaz/cardinal/Chat/TeamChat.java, src/main/java/in/twizmwaz/cardinal/match/Match.java, src/main/java/in/twizmwaz/cardinal/module/modules/team/TeamModule.java, src/main/java/in/twizmwaz/cardinal/module/modules/wools/WoolObjective.java
I know some parts are a bit messy but it all works
=> Add Chat channels and Fix wool touches 

src/main/java/in/twizmwaz/cardinal/command/CycleCommand.java
using `/cycle -f` will forcefully end the game and cycle
=> add a force flag to cycle

src/main/java/in/twizmwaz/cardinal/module/modules/team/TeamModule.java
http://gyazo.com/39afb386e10c57569da121ac52e2d3c2
=> Fixed the message on team join message.

src/main/java/in/twizmwaz/cardinal/module/ModuleFactory.java, src/main/java/in/twizmwaz/cardinal/module/modules/blitz/Blitz.java, src/main/java/in/twizmwaz/cardinal/module/modules/blitz/BlitzBuilder.java, src/main/java/in/twizmwaz/cardinal/module/modules/blitz/BlitzLives.java, src/main/java/in/twizmwaz/cardinal/module/modules/gameScoreboard/GameScoreboard.java, src/main/java/in/twizmwaz/cardinal/module/modules/rage/Rage.java, src/main/java/in/twizmwaz/cardinal/module/modules/rage/RageBuilder.java, src/main/java/in/twizmwaz/cardinal/util/TimeUtils.java
Rage works fine.
Started work on blitz - the fundamentals and logic works, the messages need to be tided up and the scoreboard needs to be implemented as well as the win condition.
=> Add Rage Module and start work on blitz

src/main/resources/lang/es.xml
Translations are from Crowdin. I only fixed some typos.
=> Add Spanish lang file with translations

src/main/resources/lang/fr.xml
Translations are from translate.oc.tc
=> added fr.xml (with translations)

src/main/java/in/twizmwaz/cardinal/module/ModuleFactory.java, src/main/java/in/twizmwaz/cardinal/module/modules/proximityAlarm/ProximityAlarm.java, src/main/java/in/twizmwaz/cardinal/module/modules/proximityAlarm/ProximityAlarmBuilder.java
Still have to add the fireworks, but I plan on adding them when I add fireworks to when an objective is completed
=> Add Proximity Alarms

src/main/java/in/twizmwaz/cardinal/util/ChatUtils.java
If you did not know warning messages can be colored 
https://github.com/OvercastNetwork/Maps/blob/3d91ac4019c8f07c7ff5486abc63923864f4f1e3/DTM/Standard/DATAbase/map.xml#L100
=> Allow warning message to accept text formatting codes

src/main/java/in/twizmwaz/cardinal/module/modules/proximityAlarm/ProximityAlarmBuilder.java
=> Remove debug message

src/main/java/in/twizmwaz/cardinal/module/modules/wools/WoolObjective.java
Fixes https://github.com/twizmwazin/CardinalPGM/issues/156
=> Fix wool pickup message

src/main/resources/lang/sv.xml
I will finish this in a few hours.
=> added sv.xml and Swedish translations

src/main/java/in/twizmwaz/cardinal/module/ModuleFactory.java, src/main/java/in/twizmwaz/cardinal/module/modules/Tnt/Tnt.java, src/main/java/in/twizmwaz/cardinal/module/modules/Tnt/TntBuilder.java, src/main/java/in/twizmwaz/cardinal/module/modules/tntTracker/TntTracker.java, src/main/java/in/twizmwaz/cardinal/util/NumUtils.java
The instant ignite is doing some weird things (the power set does not seem to be right)
and as of now I have not though of a efficient way to do the yield
=> TNT Module

src/main/java/in/twizmwaz/cardinal/module/modules/cores/CoreObjective.java, src/main/java/in/twizmwaz/cardinal/module/modules/destroyable/DestroyableObjective.java, src/main/java/in/twizmwaz/cardinal/module/modules/proximityAlarm/ProximityAlarm.java, src/main/java/in/twizmwaz/cardinal/module/modules/proximityAlarm/ProximityAlarmBuilder.java, src/main/java/in/twizmwaz/cardinal/module/modules/wools/WoolObjective.java, src/main/java/in/twizmwaz/cardinal/util/FireworkUtil.java
Basic methods to implement fireworks into other modules
=> Implement firework methods

src/main/java/in/twizmwaz/cardinal/Cardinal.java, src/main/java/in/twizmwaz/cardinal/command/WhitelistCommands.java, src/main/java/in/twizmwaz/cardinal/util/StringUtils.java
I plan to add localisation soon
=> Improved Whitelisting

src/main/java/in/twizmwaz/cardinal/Cardinal.java, src/main/java/in/twizmwaz/cardinal/GameHandler.java, src/main/java/in/twizmwaz/cardinal/cycle/CycleTimer.java, src/main/java/in/twizmwaz/cardinal/demographics/DemographicsHandler.java, src/main/java/in/twizmwaz/cardinal/match/Match.java, src/main/java/in/twizmwaz/cardinal/match/util/StartTimer.java, src/main/java/in/twizmwaz/cardinal/module/modules/blitz/Blitz.java, src/main/java/in/twizmwaz/cardinal/module/modules/teamManager/TeamManagerModule.java, src/main/java/in/twizmwaz/cardinal/rotation/Rotation.java
Also remove the imports. This fixes #220 more than twiz fixed it ;)
=> Remove JavaPlugin from GameHandler for #220

src/main/java/in/twizmwaz/cardinal/module/modules/observers/ObserverModule.java, src/main/java/in/twizmwaz/cardinal/module/modules/respawn/RespawnModule.java, src/main/java/in/twizmwaz/cardinal/module/modules/teamManager/TeamManagerModule.java, src/main/java/in/twizmwaz/cardinal/module/modules/teamPicker/TeamPicker.java, src/main/java/in/twizmwaz/cardinal/util/ItemUtils.java
A lot of it was repeating, so I just centralized some code (I was tired doing this so point out anything I missed if there's any).
=> Cleanup some item code

src/main/java/in/twizmwaz/cardinal/GameHandler.java, src/main/java/in/twizmwaz/cardinal/cycle/Cycle.java, src/main/java/in/twizmwaz/cardinal/cycle/NullChunkGenerator.java, src/main/java/in/twizmwaz/cardinal/match/Match.java, src/main/java/in/twizmwaz/cardinal/module/modules/armorKeep/ArmorKeep.java, src/main/java/in/twizmwaz/cardinal/module/modules/hill/HillObjective.java, src/main/java/in/twizmwaz/cardinal/module/modules/permissions/PermissionModule.java
=> Remove unused Player objects and use a WeakReference for World in GameHandler

src/main/java/in/twizmwaz/cardinal/command/WhitelistCommands.java
http://gyazo.com/74b69052ce7548df885eefe148c289d6
=> Fixed the message when wl is on/off

src/main/resources/lang/ko.xml
=> Add ko.xml

src/main/java/in/twizmwaz/cardinal/Cardinal.java, src/main/java/in/twizmwaz/cardinal/command/ChatCommands.java, src/main/java/in/twizmwaz/cardinal/command/ModeratorCommand.java, src/main/java/in/twizmwaz/cardinal/command/PunishmentCommands.java, src/main/java/in/twizmwaz/cardinal/command/TeamCommand.java, src/main/java/in/twizmwaz/cardinal/module/modules/permissions/PermissionModule.java, src/main/resources/config.yml
wow that is awful spelling the the commit
All complete and uptodate
=> Add permissions, closes #247

src/main/java/in/twizmwaz/cardinal/command/PunishmentCommands.java
=> Clean up punishment commands, closes #266,#263

src/main/java/in/twizmwaz/cardinal/command/JoinCommand.java, src/main/java/in/twizmwaz/cardinal/command/TeamCommand.java, src/main/java/in/twizmwaz/cardinal/module/modules/permissions/PermissionModule.java
@twizmwazin I assume you will be ok with me merging this as its a small fix and not a huge module.
=> Fix joining a team if you were already on one, fixes #274

src/main/java/in/twizmwaz/cardinal/command/ModeratorCommand.java, src/main/java/in/twizmwaz/cardinal/command/PunishmentCommands.java
When I warned him, this was the message displayed on adminchat:
Also when I /mod'd him he got this message: ChatColor.GREEN + "You are <strong>no longer</strong> a moderator"
=> Wrong warn adminchat message & "You are now a moderator" messages patch

pom.xml
Adds apache commons-lang3 to the project.
=> Fixes #301

src/main/java/in/twizmwaz/cardinal/command/ChatCommands.java
=> Fixes #303

src/main/java/in/twizmwaz/cardinal/rotation/Rotation.java, src/main/resources/config.yml
Allow users to display map.xml errors.
Sorry @twizmwazin!
=> Allow users to display map.xml errors

src/main/java/in/twizmwaz/cardinal/command/ModeratorCommand.java
I assume you are ok with me merging things like this @twizmwazin
=> Save config after adding a moderator, fixes #320

README.md
Includes spelling changes, and makes compiling clearer. Will edit wiki soon.
=> Made README clearer

src/main/java/in/twizmwaz/cardinal/module/modules/appliedRegion/type/BlockEventRegion.java, src/main/java/in/twizmwaz/cardinal/module/modules/appliedRegion/type/BlockPlaceAgainstRegion.java, src/main/java/in/twizmwaz/cardinal/module/modules/appliedRegion/type/BlockPlaceRegion.java, src/main/java/in/twizmwaz/cardinal/module/modules/buildHeight/BuildHeight.java
Small fix until SportBukkit is ready to solve completely this problem.
=> Prevent GUIs to be displayed on max height, closes #342.

src/main/java/in/twizmwaz/cardinal/command/ReadyCommand.java
http://gyazo.com/d6ac4d840f2273977f80015d4cb773d8
=> Added global message for ready command and fixed colors

src/main/java/in/twizmwaz/cardinal/command/PunishmentCommands.java
Issue:
<a href="http://imgur.com/IriPwHE"><img src="http://i.imgur.com/IriPwHE.png" title="source: imgur.com" /></a>
Solved:
<a href="http://imgur.com/2ocJCLF"><img src="http://i.imgur.com/2ocJCLF.png" title="source: imgur.com" /></a>
=> Add a space in the kick message.

src/main/java/in/twizmwaz/cardinal/module/modules/hill/HillObjective.java, src/main/java/in/twizmwaz/cardinal/module/modules/hill/HillObjectiveBuilder.java
=> Don't 'showl' a hill and make 'HillObjective' a tasked module

src/main/java/in/twizmwaz/cardinal/module/modules/destroyable/DestroyableObjective.java
forgot to put it in the commit message:
fixes #449
=> implement repairable monuments

src/main/java/in/twizmwaz/cardinal/command/StartAndEndCommand.java
=> Fix(:D) command usage

src/main/java/in/twizmwaz/cardinal/command/ChatCommands.java
=> Small typo on chat commands fix.

src/main/java/in/twizmwaz/cardinal/module/modules/bossBar/FakeWither.java
Nothing much, just renaming the fields
=> Change name of fields in FakeWither

src/main/resources/lang/zh.xml
This chinese translation is written in a slightly informal manner, wherein some words are omitted, for example "你的队" is changed to "你队" as they mean the same, but this extra "的" is only used in a more formal setting. The level of chinese used for this is at conversational level between friends, not talking to elders or the president.
A few other words of note:
I have used some of these in certain context, like the `<of>` one was pretty ambigious, so I assumed that it is used in the case of  "Page 4  of 17".
This translation was based on its english counterpart created on the 6th of March. New tags might have been added, please leave me a message telling me which new tags to add.
A bit of information on myself:
Chinese is not my dominant language, but it is one of my two master languages …
=> Added Chinese Translation

src/main/java/in/twizmwaz/cardinal/module/modules/filter/type/constant/AllWorldFilter.java
Someone was debugging and they forgot to remove a line!
=> Remove 'ayy 1' from log

src/main/resources/lang/en.xml, src/main/resources/lang/es.xml, src/main/resources/lang/fr.xml, src/main/resources/lang/it.xml, src/main/resources/lang/ko.xml, src/main/resources/lang/sv.xml
All of this translates are sourced from <a href="https://translate.oc.tc">translate.oc.tc</a>. Besides, I fixed 2 orthographical errors on es.xml.
Edit: with this PR you can close #504 & #515
=> Add modules remaining to translations

src/main/java/in/twizmwaz/cardinal/command/JoinCommand.java, src/main/java/in/twizmwaz/cardinal/command/StartAndEndCommand.java
=> Add /play and /begin commands.

src/main/java/in/twizmwaz/cardinal/module/modules/matchTranscript/MatchTranscript.java, src/main/java/in/twizmwaz/cardinal/module/modules/stats/Stats.java, src/main/resources/config.yml
=> Toggle uploading and milliseconds in transcript

src/main/java/in/twizmwaz/cardinal/module/modules/observers/ObserverModule.java
=> Prevent item frames from being rotated as an observer, fixes #537

src/main/java/in/twizmwaz/cardinal/command/RotationCommands.java, src/main/java/in/twizmwaz/cardinal/command/TeamCommand.java
All in the title and the code!
=> Add some more commands (/ml, /maplist, /mt, /myteam)

src/main/java/in/twizmwaz/cardinal/Cardinal.java, src/main/java/in/twizmwaz/cardinal/chat/ChatConstant.java, src/main/java/in/twizmwaz/cardinal/command/MiscellaneousCommands.java, src/main/resources/config.yml, src/main/resources/lang/en.xml
There we go. Added localized messages and register the command.
=> Add /say & /broadcast commands

src/main/java/in/twizmwaz/cardinal/command/ChatCommands.java
I know this isn't on Overcast but I think it might be a useful addition. There is no need merge this if you feel it is useless!
=> Add /admin (alias for /a) and /global, /shout (alias for /g)

src/main/resources/lang/ko.xml
=> Added <deathMsg> at ko.xml

src/main/resources/lang/es.xml
The same but following the feedback of @superjd10
=> Added default channels on es.xml

src/main/java/in/twizmwaz/cardinal/rank/Rank.java
=> Add rank to rank array in constructor

src/main/java/in/twizmwaz/cardinal/command/RotationCommands.java
This PR adds the commands:
* /rota
* /maprot
* /maprotation
=> Add more aliases for /rotation

src/main/java/in/twizmwaz/cardinal/command/MapCommands.java
This commit fixes #669, more information can be found there.
=> Show setnext map for /next, fixes #669

src/main/java/in/twizmwaz/cardinal/command/ProximityCommand.java, src/main/java/in/twizmwaz/cardinal/command/ScoreCommand.java
Also, now if the objective is a wool, it will show as its respective color, and the console can use ```/score```.
**Edit**: thanks @dentmaged & @CaptainElliott
=> Change messages for wools proximity, fixes #653

src/main/java/in/twizmwaz/cardinal/command/WhitelistCommands.java
=> Change message in /wl toggle

src/main/java/in/twizmwaz/cardinal/module/modules/chat/ChatModule.java
=> Deny executing /me during a global mute, fixes #680

src/main/java/in/twizmwaz/cardinal/module/modules/playable/Playable.java
This half fixes #689. Tthe issue still occurs, it just doesn't print a NullPointerException.
=> Check if the player's team is null in Playable

src/main/resources/lang/es.xml
<a href="http://imgur.com/dGJIZ4F"><img src="http://i.imgur.com/dGJIZ4F.png" title="source: imgur.com" /></a>
=> Fix order in touch message

src/main/java/in/twizmwaz/cardinal/module/modules/motd/MOTD.java, src/main/resources/config.yml
I'm not really sure exactly how people want this, so I'm going to give you guys a chance to comment on it. I like the implementation as is, let me know if you think it could be improved before this goes to master.
=> Show server message in MOTD

src/main/java/in/twizmwaz/cardinal/command/ModesCommand.java
=> Fix modes command

src/main/java/in/twizmwaz/cardinal/module/modules/scoreboard/ScoreboardModule.java
fixes #917
I already tested, @twizmwazin merge asap
=> Fix tdm Scoreboard

src/main/java/in/twizmwaz/cardinal/command/TimeLimitCommand.java, src/main/java/in/twizmwaz/cardinal/module/modules/cycleTimer/CycleTimerModule.java, src/main/java/in/twizmwaz/cardinal/module/modules/header/HeaderModule.java, src/main/java/in/twizmwaz/cardinal/module/modules/startTimer/StartTimer.java, src/main/java/in/twizmwaz/cardinal/module/modules/timeNotifications/TimeNotifications.java, src/main/java/in/twizmwaz/cardinal/util/Players.java
I want to merge this asap, to use the sound utils in ctf
=> Remove chat messages from timers
